### ISSUE TITLE
2 Smart Chains .. not working with build 16.

### ISSUE THREAD

**Issue by derwin12** [dpitts/f16v4_issues#26]
I don't know all the details but JonD and others working with a fellow on Zoom. Using release 16, could not get any test to light the lights off of a smart receiver (in dumb mode or smart mode).  Variant 16 local and 2 smart chains. (test button on receiver worked)
Rolled back to 14 and it worked in dumb and smart.

**Comment by deplanche** [comment]
A few more details on this... but I don't know all because I came into the zoom room part way thru.  But when pushing from xlights to F16v4 (build 16), the receivers would not test in smart mode (set to 16 main with 2 remotes - both remotes set to A).  When we would go to the string port webpage, it would load very slowly.  They were often cancelling out of that, and at first it looked like the data was all there.  But the End universe and End Channel (which are calculated, rather than input), did not have any values in there.  We put the controller back into 16 local port mode only thru the controller page, and all on it worked fine.  Changed back to 16  with 2 remotes set to A on the controller webpage (no xlights push this time), and still the same problem.  If we made them in dumb mode, the end universe and channel would appear on the screen, so that looked better.  But could never get the receivers to respond to the controller thru xlights or in test mode.  I suggested they go back to build 14 (that is the latest update on mine, and I knew it was working), to try that.  I had to leave before they tested that, but as Daryl indicated, that seemed to fix the problem.

**Comment by keithsw1111** [comment]
This could be the issue I saw with E131/Artnet reception which will be fixed in Build 17.

**Comment by keithsw1111** [comment]
I have published build 17 but I cant advertise it as pixelcontroller.com wont let me upload the file right now.

**Comment by keithsw1111** [comment]
I am going to close this as i believe it was fixed in build 17.

**Comment by deplanche** [comment]
Yes, that fixed the problem.
