### ISSUE TITLE
Issues with F16v4 & SK6812 RGBW using APA109 protocol as documented

### ISSUE THREAD

**Issue by magic-madrigal** [dpitts/f16v4_issues#9]
Hi Team,

I'm been working with the new F16v4 and these SK6812 leds. (https://www.amazon.com/BTF-LIGHTING-Individually-Addressable-Flexible-Non-waterproof/dp/B01N0MA729)

When using the APA109 protocol I'm not able to get the red or blue test patterns to work correctly.

I have tried all of the various LEDs orders to no avail. Any help would be welcome since I feel I'm hitting an impass.

**Comment by keithsw1111** [comment]
The test patterns wont necessarily work as you might expect. The test patterns like red ramp etc dont account for different pixel types ... they assume RGB.  So a red ramp outputs R..R..R..R..R..R.. but because your pixels are RGBW it will output R..W..B..G..R.. etc. This is not a problem ... just way the test patterns actually work.

**Comment by keithsw1111** [comment]
SK6812WW ... is that SK6812RGBW ... ie 4 channel or is it something else again. We have SK6812 RGB which are just WS2811 and SK6812RGBW which are APA109 ... essentially WS2811 but with 4 channels for 4 colours. Is SK6812 a 5 channel version?

**Comment by keithsw1111** [comment]
Can I now close this?

**Comment by rvcullen** [comment]
Yes, apologies. I had to resend the new protocol to boarda few times and then it was working. Not sure what happened.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
